title: Davide Artuso Official Website
description: "Il sito web ufficiale di davide Artuso."
url: "https://davide.artuso.me/"
baseurl: /davideart.github.io

author:
  name: "@davideart"

github: davideart/davideart.github.io

permalink: /:title/

header_pages:
  - index.html
  - demo/index.md

sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - documentation.md
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - Gemfile
  - Gemfile.lock
  - .github
  - vendor
